[package]
authors = ["too-r <william.huddie@gmail.com>"]
name = "discordbot"
version = "0.1.0"
[dependencies]
discord = "0.8.0"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "*"
toml = "0.4.2"
